"""empty message

Revision ID: f42fb97fddb9
Revises: 
Create Date: 2018-07-21 12:58:07.573516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42fb97fddb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commented_official_school_name', sa.String(length=255), nullable=True),
    sa.Column('author_avatar', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=50), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_review', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.place_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_time'), 'comment', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_time'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
